"use client";
import { useState } from "react";
import type { ConditionType,Strategy } from "@huxtrade/shared-types";
import { publicApi } from "../lib/api";

const all:ConditionType[]=["OI","CVD","FUNDING","HEATMAP"];
const blank={name:"",enabled:false,logic:"AND" as "AND"|"N_OF_M",requiredCount:2,conditions:[...all] as ConditionType[],heatmapRange:"24h" as Strategy["heatmapRange"],maxOrdersPerSide:5};

export function StrategyManager({initial}:{initial:Strategy[]}){
  const [items,setItems]=useState(initial);const [message,setMessage]=useState("");const [editingId,setEditingId]=useState<string|null>(null);const [form,setForm]=useState(blank);
  function toggleCondition(condition:ConditionType){setForm({...form,conditions:form.conditions.includes(condition)?form.conditions.filter((value)=>value!==condition):[...form.conditions,condition]});}
  function edit(strategy:Strategy){setEditingId(strategy.id);setForm({name:strategy.name,enabled:strategy.enabled,logic:strategy.logic,requiredCount:strategy.requiredCount??2,conditions:[...strategy.conditions],heatmapRange:strategy.heatmapRange,maxOrdersPerSide:strategy.maxOrdersPerSide});setMessage("编辑运行中的策略会撤销其未成交限价单");}
  function reset(){setEditingId(null);setForm(blank);}
  async function submit(event:React.FormEvent){event.preventDefault();const response=await fetch(`${publicApi}/api/strategies${editingId?`/${editingId}`:""}`,{method:editingId?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)});const body=await response.json();if(!response.ok){setMessage(`保存失败：${body.message??body.error}`);return;}setItems(editingId?items.map((item)=>item.id===editingId?body:form.enabled?{...item,enabled:false}:item):form.enabled?[...items.map((item)=>({...item,enabled:false})),body]:[...items,body]);setMessage("策略已保存");reset();}
  async function enable(id:string){await fetch(`${publicApi}/api/strategies/${id}/enable`,{method:"POST"});setItems(items.map((item)=>({...item,enabled:item.id===id})));}
  async function remove(strategy:Strategy){if(!window.confirm(`确认删除策略 ${strategy.name}？`))return;const response=await fetch(`${publicApi}/api/strategies/${strategy.id}`,{method:"DELETE"});if(response.ok){setItems(items.filter((item)=>item.id!==strategy.id));setMessage("策略已删除");}else{const body=await response.json();setMessage(body.message??"删除失败");}}
  return <div className="pageGrid">
    <section className="panel"><div className="panelHead"><div><h2>{editingId?"编辑确定性策略":"创建确定性策略"}</h2><small>每类条件最多一次；做空方向由系统镜像</small></div>{editingId&&<button className="btn" onClick={reset}>取消编辑</button>}</div>
      <form className="formGrid" onSubmit={submit}><div className="field"><label>策略名称</label><input required value={form.name} onChange={(event)=>setForm({...form,name:event.target.value})} placeholder="Core Four-Factor"/></div><div className="field"><label>组合逻辑</label><select value={form.logic} onChange={(event)=>setForm({...form,logic:event.target.value as "AND"|"N_OF_M"})}><option value="AND">全部满足 · AND</option><option value="N_OF_M">至少 N 个满足</option></select></div><div className="field"><label>Heatmap 周期</label><select value={form.heatmapRange} onChange={(event)=>setForm({...form,heatmapRange:event.target.value as Strategy["heatmapRange"]})}>{["12h","24h","3d","7d","30d"].map((value)=><option key={value}>{value}</option>)}</select></div><div className="field"><label>同币同方向综合上限</label><input type="number" min="1" max="20" value={form.maxOrdersPerSide} onChange={(event)=>setForm({...form,maxOrdersPerSide:Number(event.target.value)})}/></div><div className="field"><label>条件 · 选择 2–4 项</label><div className="checkboxes">{all.map((condition)=><label key={condition}><input type="checkbox" checked={form.conditions.includes(condition)} onChange={()=>toggleCondition(condition)}/>{condition}</label>)}</div></div>{form.logic==="N_OF_M"&&<div className="field"><label>N</label><input type="number" min="2" max={form.conditions.length} value={form.requiredCount} onChange={(event)=>setForm({...form,requiredCount:Number(event.target.value)})}/></div>}<div className="checkboxes"><label><input type="checkbox" checked={form.enabled} onChange={(event)=>setForm({...form,enabled:event.target.checked})}/> 保存后立即成为唯一运行策略</label></div><div className="toolbar"><button className="btn primary">{editingId?"更新策略":"保存策略"}</button><span className="subtle">{message}</span></div></form>
    </section>
    <section className="panel"><div className="panelHead"><h2>策略库</h2><small>同时只运行一套</small></div><table><thead><tr><th>策略</th><th>逻辑</th><th>条件</th><th>Heatmap</th><th>订单上限</th><th>状态</th><th>操作</th></tr></thead><tbody>{items.map((strategy)=><tr key={strategy.id}><td><b>{strategy.name}</b></td><td>{strategy.logic==="AND"?"AND":`${strategy.requiredCount} / ${strategy.conditions.length}`}</td><td className="mono">{strategy.conditions.join(" · ")}</td><td>{strategy.heatmapRange}</td><td>{strategy.maxOrdersPerSide}</td><td><span className={`tag ${strategy.enabled?"":"orange"}`}>{strategy.enabled?"RUNNING":"STOPPED"}</span></td><td><div className="toolbar"><button className="btn" onClick={()=>edit(strategy)}>编辑</button>{!strategy.enabled&&<button className="btn primary" onClick={()=>enable(strategy.id)}>启用</button>}<button className="btn danger" disabled={strategy.enabled} onClick={()=>remove(strategy)}>删除</button></div></td></tr>)}{!items.length&&<tr><td colSpan={7} className="empty">尚未创建策略</td></tr>}</tbody></table></section>
  </div>;
}
