import { Header } from "../../components/Header";
import { SystemSettings } from "../../components/SystemSettings";
import { api } from "../../lib/api";

export const dynamic="force-dynamic";
type Health={services:Array<Record<string,unknown>>;assets:Array<Record<string,unknown>>;errors:Array<Record<string,unknown>>;lastScan:Record<string,unknown>|null};

export default async function Page(){
  const [status,preferences,health]=await Promise.all([
    api<Record<string,unknown>>("/api/settings/status",{coinglassConfigured:false,telegramConfigured:false,variationalMode:"disabled",liveTradingEnabled:false}),
    api<Array<{event_type:string;enabled:boolean}>>("/api/settings/notifications",[]),
    api<Health>("/api/health/details",{services:[],assets:[],errors:[],lastScan:null})
  ]);
  return <><Header eyebrow="Operations & Safety" title="系统设置与健康"/><div className="pageGrid">
    <section className="panel"><div className="panelHead"><h2>执行安全门</h2><span className={`tag ${status.liveTradingEnabled?"":"orange"}`}>{status.liveTradingEnabled?"LIVE":"LOCKED"}</span></div><div className="split"><div><div className="bigStatus">{String(status.variationalMode).toUpperCase()}</div><p className="subtle">Variational 适配器模式 · 完成协议发现前保持 disabled</p></div><div><span className="subtle">CoinGlass API</span><p className={status.coinglassConfigured?"up":"warn"}>{status.coinglassConfigured?"已配置":"未配置"}</p></div></div><div className="divider"/><p className="subtle">真实资金执行需要：会话有效、启动对账完成、30 天数据预热完成、币种交易开关开启，并显式设置 LIVE_TRADING_ENABLED=true。任一项失败均拒绝提交。</p></section>
    <section className="panel"><div className="panelHead"><div><h2>服务健康</h2><small>失败次数、最后成功时间与交易阻断状态</small></div><span className={`tag ${health.lastScan?.status==="COMPLETED"?"":"orange"}`}>SCAN {String(health.lastScan?.status??"NO DATA")}</span></div><table><thead><tr><th>服务</th><th>状态</th><th>连续失败</th><th>最后成功</th><th>错误</th><th>交易</th></tr></thead><tbody>{health.services.map((service)=><tr key={String(service.service)}><td><b>{String(service.service)}</b></td><td><span className={`tag ${service.state==="healthy"?"":"orange"}`}>{String(service.state).toUpperCase()}</span></td><td>{String(service.consecutive_failures)}</td><td>{service.last_success_at?new Date(String(service.last_success_at)).toLocaleString("zh-CN",{timeZone:"Asia/Shanghai"}):"—"}</td><td className="subtle">{String(service.error??"—")}</td><td className={service.blocks_trading?"down":"up"}>{service.blocks_trading?"阻断":"允许"}</td></tr>)}{!health.services.length&&<tr><td colSpan={6} className="empty">等待服务上报健康状态</td></tr>}</tbody></table></section>
    <section className="panel"><div className="panelHead"><h2>单币数据新鲜度</h2><small>Binance 超过 5 分钟或 Heatmap 超过 30 分钟会触发单币暂停</small></div><table><thead><tr><th>币种</th><th>最近收盘</th><th>快照年龄</th><th>30D 预热</th><th>暂停</th><th>原因</th></tr></thead><tbody>{health.assets.map((asset)=><tr key={String(asset.code)}><td><b>{String(asset.code)}</b></td><td>{asset.closed_at?new Date(String(asset.closed_at)).toLocaleString("zh-CN",{timeZone:"Asia/Shanghai"}):"—"}</td><td>{asset.age_seconds==null?"—":`${Math.round(Number(asset.age_seconds)/60)} 分钟`}</td><td><span className={`tag ${asset.warmup_ready?"":"orange"}`}>{asset.warmup_ready?"READY":"WARMING"}</span></td><td>{asset.paused?"是":"否"}</td><td className="subtle">{String(asset.pause_reason??"—")}</td></tr>)}{!health.assets.length&&<tr><td colSpan={6} className="empty">尚未配置币种</td></tr>}</tbody></table></section>
    <section className="panel"><div className="panelHead"><h2>永久错误记录</h2><small>最近 100 条 · 数据库不自动清理</small></div><table><thead><tr><th>发生时间</th><th>服务</th><th>币种</th><th>代码</th><th>错误</th><th>交易</th></tr></thead><tbody>{health.errors.map((error)=><tr key={String(error.id)}><td>{new Date(String(error.occurred_at)).toLocaleString("zh-CN",{timeZone:"Asia/Shanghai"})}</td><td>{String(error.service)}</td><td>{String(error.asset_code??"—")}</td><td className="mono">{String(error.code)}</td><td className="subtle">{String(error.message)}</td><td className={error.blocks_trading?"down":"up"}>{error.blocks_trading?"阻断":"不阻断"}</td></tr>)}{!health.errors.length&&<tr><td colSpan={6} className="empty">尚无业务错误记录</td></tr>}</tbody></table></section>
    <SystemSettings status={status} initialPreferences={preferences}/>
  </div></>;
}
